SELECT TOP (1000) [Country]
      ,[Region]
      ,[Population]
      ,[Area_sq_mi]
      ,[Pop_Density_per_sq_mi]
      ,[Coastline_coast_area_ratio]
      ,[Net_migration]
      ,[Infant_mortality_per_1000_births]
      ,[GDP_per_capita]
      ,[Literacy]
      ,[Phones_per_1000]
      ,[Arable]
      ,[Crops]
      ,[Other]
      ,[Climate]
      ,[Birthrate]
      ,[Deathrate]
      ,[Agriculture]
      ,[Industry]
      ,[Service]
  FROM [Countries].[dbo].[world]